GET http://localhost:8081/items

POST http://localhost:8081/item
Content-Type: application/json

{"username": "AAA", "sum": 1000}

###
POST http://localhost:8081/item
Content-Type: application/json

{"username": "AAB", "sum": 300}

GET http://localhost:8081/items